#
# IMPORTANT NOTE: This conf file would never be in the repository
# It has been included for testing and verification purposes
#
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports: ["2181:2181"]

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports: ["9092:9092", "9093:9093"]
    depends_on:
      zookeeper:
        condition: service_started
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: OUTSIDE
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "xm-companies:1:1"
