#
# IMPORTANT NOTE: This conf file would never be in the repository
# It has been included for testing and verification purposes
#

include:
  - ./compose-kafka.yml
  - ./compose-mysql.yml

services:

  producer:
    build: ./producer
    container_name: producer
    ports: ["3000:3000"]
    depends_on:
      mysql:
        condition: service_started
      kafka:
        condition: service_started
    environment:
      APP_ENV: "dev"
      ADDR: "3000"
      JWT_KEY: 387118194ac5b7846ea907983ae125464eb4122339e7230683958239b11e885d
      KAFKA_TOPIC: "xm-companies"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_MESSAGE_TIMEOUT: 5000
      KAFKA_RETRIES: 10
      KAFKA_RETRY_BACKOFF: 500
      DB_HOST: mysql
      DB_NAME: xm_tech_test
      DB_USER: xm
      DB_PASS: secret
